name: Img Scanning

on:
  push:
    branches: [ master ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frik0/test:1.0   
    
    - name: Push
      run: docker push frik0/test:1.0
      
    - name: Scan Container Image
      id: scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: frik0/test:1.0
        
    - name: test
      run: echo ${{ steps.scan.outputs.scan-report-path }}
      
    - name: test2
      run: cat ${{ steps.scan.outputs.scan-report-path }}
    
    - name: Convert Container Scan Report to SARIF
      id: scan-to-sarif
      uses: rm3l/container-scan-to-sarif-action@v1.5.0
      if: ${{ always() }}
      with:
        input-file:  ${{ steps.scan.outputs.scan-report-path }}

      
    - name: Upload SARIF reports to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() }}
      with:
        sarif_file: ${{ steps.scan-to-sarif.outputs.sarif-report-path }}
